FORBIDDEN_VENDOR_KEYWORDS = [
    "KSManage Ultra",
    "Inspur",
    "IEI",
    "IEISYSTEM",
    "MAGINFRA",
    "AIVRES",
    "浪潮",
    "至索",
    "inspur.com",
    "ieisystem.com",
    "magiops",
    "maginfra.com",
    "aivres.com",
    "@inspur.com",
    "@ieisystem.com",
    "@maginfra.com",
    "@aivres.com",
    "400-860-0011",
    "800-860-0011",
    "山东省济南市",
]
